# Generated by Django 5.1.1 on 2024-11-18 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judge',
            name='user',
        ),
    ]
